
#ifndef _PARAGRAPH_HEADER
#define _PARAGRAPH_HEADER
 
#define STS_MEGA_PARAMETERS  200
#define STS_MEGA_CODES 209
#define STS_MEGA_GENERAL_PARAMETERS 210
#define STS_MEGA_CROSS_SECTION 215
#define STS_MEGA_Material_properties 220
#define STS_MEGA_Creep_coefficient_concrete 225
#define STS_MEGA_Loadinfo 226
#define STS_MEGA_Load_cases 230
#define STS_MEGA_Calculation_parameters 235
#define STS_MEGA_Load_combinations 245

#define STS_MEGA_ULTIMATE_LIMIT_STATES 320
#define STS_MEGA_RESISTANCE_OF_THE_CROSS_SECTION_AXIAL  325
#define STS_MEGA_RESISTANCE_OF_THE_CROSS_SECTION_TO_SHEAR_RESISTANCE 330
#define STS_MEGA_RESISTANCE_OF_THE_CROSS_SECTION_TO_COMBINED_ACTIONS_M_N 335
#define STS_MEGA_RESISTANCE_OF_THE_CROSS_SECTION_TO_COMBINED_ACTIONS_M_N2 336
#define STS_MEGA_BUCKLING_RESISTANCE_TO_AXIAL_FORCE 340
#define STS_MEGA_AMPLIFICATION_OF_DESIGN_MOMENT_OF_COMBINED_ACTION_M_N_CONSIDERING 345
#define STS_MEGA_INTERFACE_SHEAR_CONNECTION 350
#define STS_MEGA_SYNTHESIS_OF_VERIFICATIONS 355
#define STS_MEGA_SYNTHESIS_OF_VERIFICATIONS2 356
#define STS_MEGA_CRACKCHECK 360
#define STS_MEGA_MEMBERCHECK 365


#define STS_MEGA_SERVICEABILITY_LIMIT_STATES 410
#define STS_MEGA_INTERNAL_FORCES  425
#define STS_MEGA_CRACK_CHECK    435
#define STS_MEGA_MEMBER_CHECK1   445
#define STS_MEGA_MEMBER_CHECK2   455
#define STS_MEGA_MEMBER_CHECK3   465
#define STS_MEGA_MEMBER_CHECK4   475


#define STS_STRUCT_FIBER_1      610
#define STS_STRUCT_PDM_1        620
#define STS_STRUCT_SECTION      630
#define STS_STRUCT_FIBER_2      640
#define STS_STRUCT_PDM_2        650

#endif // _PARAGRAPH_HEADER


